name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 28.1
          - 29.1
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v4
      - name: Run tests
        run: make package-lint
